{
  "language": "cpp",
  "os": [
    "linux"
  ],
  "dist": "trusty",
  "sudo": true,
  "services": [
    "docker"
  ],
  "script": [
    "sudo docker build -f Dockerfile -t samp_ac_v2:latest ."
  ]
}
