version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Win32
build:
  project: acv2.sln
  verbosity: minimal
artifacts:
  - path: C:\projects\samp-ac-v2\Release\samp_launcher.exe
    name: my-artifact
